# Numpy Tutorial

Wiki:

NumPy是Python語言的一個擴充程式庫。支援高階大量的維度陣列與矩陣運算，此外也針對陣列運算提供大量的數學函式函式庫。

NumPy的核心功能是ndarray（即n-dimensional array，多維陣列）資料結構。這是一個表示多維度、同質並且固定大小的陣列物件。而由一個與此陣列相關聯的資料型態物件來描述其陣列元素的資料格式（例如其字元組順序、在記憶體中佔用的字元組數量、整數或者浮點數等等）。

* Reference links
    * [A Visual Intro to NumPy and Data Representation](http://jalammar.github.io/visual-numpy/)

In [1]:
import numpy as np

## BASICS

In [2]:
[1, 1] * 3 # 註解

[1, 1, 1, 1, 1, 1]

In [3]:
print([1, 1] * 3) # list

[1, 1, 1, 1, 1, 1]


In [4]:
np.array([1, 1]) * 3 # array

array([3, 3])

In [5]:
print(np.array([1, 1]) * 3)

[3 3]


In [6]:
a = np.array([1, 2, 3]) # array  
print(a)

b = np.array( [[1., 1., 1.], # row:0   #橫 row 直 column
         [1., 1., 1.]] ) # row:1

print(b)

[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(a.ndim) # 維
print(b.ndim)

1
2


In [7]:
a = np.array([1, 2, 3])

b = np.array([
    [1., 1., 1.], # row:0   #橫 row 直 column
    [1., 1., 1.] # row:1
])

c = np.array([1, 2, 3], dtype="int32")
print(a.dtype, b.dtype, c.dtype)

int32 float64 int32


In [ ]:
print(a.size)
print(b.size)
print(c.size)

3
6
3


In [ ]:
print(a) # not list!! no ','!
print(b)
print(c)

[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]


In [ ]:
print(a.shape)
print(b.shape) # row, col
print(c.shape)

(3,)
(2, 3)
(3,)


In [ ]:
b.shape[0]

2

In [ ]:
b.shape[1]

3

In [ ]:
print(a)
print(b)
print(c)
print('-------')
print(a.ndim)
print(b.ndim)
print(c.ndim)
print('-------')
print(a.shape)
print(b.shape)
print(c.shape)
print('-------')
print(a.size)
print(b.size)
print(c.size)

[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]
-------
1
2
1
-------
(3,)
(2, 3)
(3,)
-------
3
6
3


In [ ]:
np.array([1,2,3]).shape # not row or column

(3,)

In [ ]:
print(np.array([[1,2,3]])) # 2-d

np.array([[1,2,3]]).shape # 1 row, 3 columns

[[1 2 3]]


(1, 3)

In [ ]:
print(np.array([[1],[2],[3]])) # 3 rows  1 column
np.array([[1],[2],[3]]).shape

[[1]
 [2]
 [3]]


(3, 1)

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([1,2,3]).shape

(3,)

* **Numpy Benefits**

    1) Fixed Type
    
    2) Contiguous memory

    3) Array 可運算 List or Tuple 不可運算


In [ ]:
# get type
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
int32


In [ ]:
# get size - itemsize (bytes) of each item (B) # 1 byte = 8 bits # 64 bits = 8 bytes
print(a.dtype, a.itemsize) # 64/8 = 8  bytes
print(b.dtype, b.itemsize)
print(c.dtype, c.itemsize)

int64 8
float64 8
int32 4


In [ ]:
a

array([1, 2, 3])

In [ ]:
# get total size - total space used (Bytes)
print(a.size * a.itemsize) # 3 * 8
print(a.size, a.itemsize, a.nbytes)
print(b.size, b.itemsize, b.nbytes)
print(c.size, c.itemsize, c.nbytes)

24
3 8 24
6 8 48
3 4 12


In [ ]:
arr = [range(1, 5), range(5, 9)] # list of range
print(type(arr))
print(arr)

e = np.array(arr) # 2d array
print(type(e))
print(e)

x = e.tolist() # convert array back to list 
print(type(x))
print(x)

<class 'list'>
[range(1, 5), range(5, 9)]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'list'>
[[1, 2, 3, 4], [5, 6, 7, 8]]


## Adding and removing elements from numpy arrays

In [ ]:
a = np.arange(24) # np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
print(a.shape)

(24,)


In [ ]:
a = np.arange(24).reshape((3,8))
print(a.shape)
print(a)

(3, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
a = np.arange(24).reshape((2, 3, 4)) # 3-d, consisting of two 2-d arrays, each array has 3 rows 4 columns
print(a.ndim)
print(a.shape)
print(a)

3
(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b = np.append(a, [5, 6, 7, 8]) # append to 1-d
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [ ]:
b.shape # 1-d

(28,)

In [ ]:
b.reshape((7, 4)) # 1-d to 2-d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.shape

(2, 3, 4)

In [ ]:
c = a * 10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
np.append(a, c, axis=0) # axis=0 -> 組方向

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
np.append(a, c, axis=0).shape # a c (2,3,4) -> (4,3,4)

(4, 3, 4)

In [ ]:
np.append(a, c, axis=1) # (2,3,4) -> (2,6,4)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
np.append(a, c, axis=1).shape

(2, 6, 4)

In [ ]:
np.append(a, c, axis=2) # (2,3,4) -> (2,3,8)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [ ]:
np.append(a, c, axis=2).shape

(2, 3, 8)

In [ ]:
np.append(a, c) # append to 1-d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,   3,  13,
        23,  33,  43,  53,  63,  73,  83,  93, 103, 113, 123, 133, 143,
       153, 163, 173, 183, 193, 203, 213, 223, 233])

In [ ]:
np.append(a, c).shape # append to 1-d without specifying axis

(48,)

In [ ]:
f = np.arange(0,12).reshape((3,4)) # Exercise
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
g = f * 10 + 5 # Exercise
g

array([[  5,  15,  25,  35],
       [ 45,  55,  65,  75],
       [ 85,  95, 105, 115]])

In [ ]:
np.append(f, g, axis=0).shape # Exercise

(6, 4)

In [ ]:
np.append(f, g, axis=0) # Exercise

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [  5,  15,  25,  35],
       [ 45,  55,  65,  75],
       [ 85,  95, 105, 115]])

In [ ]:
np.append(f, g, axis=1).shape # Exercise

(3, 8)

In [ ]:
np.append(f, g, axis=1) # Exercise

array([[  0,   1,   2,   3,   5,  15,  25,  35],
       [  4,   5,   6,   7,  45,  55,  65,  75],
       [  8,   9,  10,  11,  85,  95, 105, 115]])

In [ ]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
c.shape

(2, 3, 4)

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis=0) # 0axis 1位置 略
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis=1)
after_insert_array

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis=2)
after_insert_array

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [ ]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
d = np.empty(c.shape) # d = np.empty((2, 3, 4))
np.copyto(d, c)
d # d = np.copy(c)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [ ]:
np.delete(d, 1, axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [ ]:
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [ ]:
np.delete(d, 1, axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [ ]:
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [ ]:
e = np.delete(d, 1, axis=2)
e

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

In [ ]:
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

## Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [ ]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[1][2]

10

In [ ]:
# get a specific element [r, c]
print(a[1, 5])
print(a[1][5])
print(a[1][-2])

13
13
13


In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
#  get a specific row
a[0, :] # a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# get a specific col
a[:, 2]

array([ 3, 10])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# getting fancy [startindex: endindex: stepsize] endindex not included
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[1, 1:6:1]

array([ 9, 10, 11, 12, 13])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# changing element(s)
a [1, 5] = 20
print(a)
print('-----')
a[:, 2] = 5
print(a)
print('-----')
a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
-----
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
-----
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3-d
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
print('------')
print(a.shape)

# think of number of rows as original number of rows
# inside each box columns become rows and depth becomes columns
# think of it as [1, 2] at at position a[0, 0]

# NumPy’s order for printing n-dimensional arrays is that the last axis
# is looped over the fastest, while the first is the slowest

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------
(2, 2, 2)


In [ ]:
print(a[0, 0]) # = a[0, 0, :]
print(a[0, 1])
print(a[1, 0])
print(a[1, 1])

# get specific element
print(a[0,1,1])

[1 2]
[3 4]
[5 6]
[7 8]
4


In [ ]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# replace # Exercise

a[:, 1, :] = [[10, 11], [12, 13]]
print(a)
print('-----')

# a[0, 1, :] = [99, 98]
a[0, 1] = [99, 98]
print(a)

[[[ 1  2]
  [10 11]]

 [[ 5  6]
  [12 13]]]
-----
[[[ 1  2]
  [99 98]]

 [[ 5  6]
  [12 13]]]


## Initializing different type of arrays

In [ ]:
# all 0's matrix
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# all 1's matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# any other number (full_like)
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
np.full_like(a, 8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [ ]:
# random decimal numbers
np.random.rand(4, 2, 3) # uniform distribution [0,1) # np.random.randn => std normal distribution

array([[[0.79352159, 0.63814702, 0.13345359],
        [0.82210728, 0.99066863, 0.14421068]],

       [[0.47504328, 0.04475688, 0.99192087],
        [0.80056464, 0.65726207, 0.94661048]],

       [[0.61348609, 0.56125509, 0.36538642],
        [0.17925172, 0.89814463, 0.51755681]],

       [[0.3973632 , 0.42605719, 0.42433273],
        [0.44031873, 0.56397012, 0.96779462]]])

In [ ]:
np.random.random_sample(4, 2, 3)

TypeError: ignored

In [ ]:
np.random.random_sample((4, 2, 3)) # uniform distribution [0,1)

array([[[0.2529175 , 0.53846651, 0.89399832],
        [0.72909165, 0.16997689, 0.68508731]],

       [[0.0179452 , 0.00694638, 0.53002444],
        [0.72574092, 0.38930213, 0.18831088]],

       [[0.1101829 , 0.6588632 , 0.15192472],
        [0.05575746, 0.49784078, 0.79272582]],

       [[0.75597421, 0.58841609, 0.68047447],
        [0.88840745, 0.89445225, 0.67011927]]])

In [ ]:
np.random.random_sample(a.shape) # np.random.random_sample((2,8)), uniform distribution [0,1)

array([[0.8604243 , 0.66457853, 0.64860038, 0.24266356, 0.10388281,
        0.96661683, 0.73548277],
       [0.59557949, 0.18703322, 0.42408809, 0.33223854, 0.38630098,
        0.32332654, 0.01016243]])

In [ ]:
# random integer values
print(np.random.randint(7)) # from [0,1,2,3,4,5,6]
print(np.random.randint(7, size=(3, 3)))

5
[[3 1 2]
 [4 6 4]
 [6 5 3]]


In [ ]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat an array 略

arr = np.array([[1, 2, 3]]) # (1,3)
r1 = np.repeat(arr, 3, axis=0) # (1x3,3)
print(r1)
print('-----')
r2 = np.repeat(arr, 3, axis=1) # (1,3x3)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
-----
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
#  creating a customized array
output = np.ones((5, 5))
print(output)
print('-----')

z = np.zeros((3, 3))
print(z)
print('-----')
z[1, 1] = 9
print(z)
print('-----')

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
-----
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# careful while copying
a = np.array([1, 2, 3])
b = a # just points
b [0]= 100
print(a)
print(b)
print('-----')

a = np.array([1, 2, 3])
b = a.copy()
b [0]= 100
print(a)
print(b)


[100   2   3]
[100   2   3]
-----
[1 2 3]
[100   2   3]


In [ ]:
# adding an axis
a = np.array([0, 1])
print(a.shape)
print(a) # not row or col
a_col = a[:, np.newaxis]
print(a_col)
print(a_col.shape)

(2,)
[0 1]
[[0]
 [1]]
(2, 1)


In [ ]:
# adding an axis
a = np.array([0, 1])
a_col = np.expand_dims(a, axis=-1)
print(a_col)

[[0]
 [1]]


In [ ]:
# adding an axis
a = np.array([0, 1])
a_col = a[:, None] # 2 x 1
print(a_col)

[[0]
 [1]]


In [ ]:
a_col = a[None, :] # 1 x 2
print(a_col)

[[0 1]]


In [ ]:
print(a_col) # (1,2)
a_col.T # (2,1)

[[0 1]]


array([[0],
       [1]])

In [ ]:
print(a_col.shape)
print(a_col.T.shape)

(1, 2)
(2, 1)


In [ ]:
# flatten array
# always returns a flat copy of the original array
arr = np.arange(10, dtype=float).reshape((2, 5))
arr_flat = arr.flatten()
arr_flat[0] = 33

print(arr)
print(arr_flat) # arr.flatten | a flat copy | np.copy()

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [ ]:
# creating evenly spaced number over an specified interval

np.linspace(start = 5, stop=15, num=11)
print(np.linspace(5, 15, 11))

print(np.linspace(5, 15, 11, retstep=True))

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]), 1.0)


In [ ]:
# Exercises 0
#1. Create a null(zero) vector (1-d array) of size 10 but the fifth value is 1

#2. Create a 3x3 array with values ranging from 0 to 8

#3. Create a 2d (5x5) array with 1 on the border and 0 inside

#4. Create a 3x3x3 array with random values of uniform distribution [0,1)

## Mathematics

In [ ]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b = np.array([1, 0, 1, 0])

In [ ]:
a + b


array([2, 2, 4, 4])

In [ ]:
a * b

array([1, 0, 3, 0])

In [ ]:
np.sin(a) 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### linear algebra


In [ ]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]]) # 2-d
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [ ]:
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [ ]:
my_first_matrix.I # inverse of matrix

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [ ]:
# compute the eigenvalues and eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))

### statistics

In [ ]:
import numpy as np

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
print(np.min(stats, axis=0)) # 結果是一 row
print(np.min(stats, axis=1)) # 結果是一 column

print(np.max(stats, axis=0))
print(np.max(stats, axis=1))

[1 2 3]
[1 4]
[4 5 6]
[3 6]


In [ ]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(stats, axis=0) # 結果是 1 row

array([5, 7, 9])

In [ ]:
rnd = np.random.randn(4, 2) # random normals in 4x2 array
print(rnd)
print(rnd.mean())
print(rnd.std())
print(rnd.argmin()) # index of minimum element
print(rnd.sum())
print(rnd.sum(axis=0)) # sum of columns # 結果是一 row (axis=0)
print(rnd.sum(axis=1)) # sum of rows # 結果是一 column (axis=1)

[[ 0.75011051 -0.56856497]
 [ 0.08161791 -0.23674663]
 [-0.68454025  0.02496519]
 [ 0.25839553 -1.08477145]]
-0.18244176856672661
0.5471606625329993
7
-1.459534148533813
[ 0.40558371 -1.86511786]
[ 0.18154554 -0.15512872 -0.65957505 -0.82637592]


### boolean masking and advanced indexing

In [ ]:
# we can index using a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]] # a[1], a[[1]]

array([2, 3, 9])

In [ ]:
filedata = np.arange(30).reshape((3,10))
filedata

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
filedata > 15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
filedata[filedata > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
filedata

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.any(filedata > 15, axis= 0) # 結果是一 row (axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
np.all(filedata > 15, axis= 0) # 結果是一 row

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
filedata

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
(filedata > 15) & (filedata < 25) # numpy 交集 &; 聯集 |

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False]])

In [ ]:
~((filedata > 15) & (filedata < 25)) # ~ -> 相反

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [ ]:
filedata[((filedata > 15) & (filedata < 25))]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
print(0 == (17 % 7)) # == 布林運算子, (= assign)

False


In [ ]:
print(0 == (0 % 7)) # == 布林運算

True


In [ ]:
# zero_mod_7_mask =  0 == (my_vector % 7) # too many = ???

In [ ]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105]) # assign
print(0 == (my_vector % 7)) # == 布林運算
zero_mod_7_mask =  0 == (my_vector % 7) # = assign | == 布林運算
print(zero_mod_7_mask)

[False False  True False  True False  True]
[False False  True False  True False  True]


In [ ]:
my_vector[zero_mod_7_mask]

array([  0,  21, 105])

In [ ]:
mod_test = 0 == (my_vector % 7)
posmask = my_vector > 0
combined_mask = np.logical_and(mod_test, posmask) # &
# combined_mask
print(my_vector)
print('-----------')
print(mod_test)
print('-----------')
print(posmask)
print('-----------')
print(combined_mask)
print('-----------')
print( (0 == (my_vector % 7)) & (my_vector > 0) )
print( (0 == (my_vector % 7)) | (my_vector > 0) )

print(my_vector[combined_mask])
print(my_vector[ (0 == (my_vector % 7)) & (my_vector > 0) ])
print(my_vector[ (0 == (my_vector % 7)) and (my_vector > 0) ]) # error

[-17  -4   0   2  21  37 105]
-----------
[False False  True False  True False  True]
-----------
[False False False  True  True  True  True]
-----------
[False False False False  True False  True]
-----------
[False False False False  True False  True]
[False False  True  True  True  True  True]
[ 21 105]
[ 21 105]


ValueError: ignored

In [ ]:
#  example indexing
a = np.arange(1, 11).reshape((2, 5))
b = np.arange(11, 21).reshape((2, 5))
c = np.arange(21, 31).reshape((2, 5))

In [ ]:
final = np.vstack([a, b, c])
print(final)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
final[2:4, :2]

array([[11, 12],
       [16, 17]])

In [ ]:
final[[0, 1, 2, 3], [1, 2, 3, 4]] # [[row index], [col index]], one vs one

array([ 2,  8, 14, 20])

In [ ]:
final

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
final[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
# excercise 1

# players = [56, 8, 19, 14, 6, 71]   # list 球隊人數                                        
# teams = ['Apple', 'Orange', 'pineApple', 'Big Apple', 'Bananna', 'Cherry'] # list 球隊 Team

#Players 總共有幾人 ? 

#Teams 總共有幾隊 ? 

#最多的人的 team 是幾人 ?

#最多的人的 team 是哪個 team ?  即哪一隊最多人 ?

#人數大於 10 的組別 ?

#除了cherry組以外的 players 總數 ?


## Rearranging array elements

In [ ]:
before = np.array([[1, 2, 3 , 4], [5, 6, 7, 8]]) # 略
print(before)

print(before.reshape((8,1)))

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# vertically stacking arrays # 略
v1 = np.array([1, 2, 3, 4])
v2 = np.array([11, 22, 33, 44])

np.vstack((v1, v2, v2))

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [ ]:
# horizontal stacking # 略
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)
print(np.hstack((h1, h2))) # (2,6)
np.vstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


ValueError: ignored

In [ ]:
my_start_array = np.arange(24) # 略
my_3_8_array = my_start_array.reshape((3, 8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [ ]:
# fliplr - flip left right is equivalent to slice [:, ::-1]. The array flips along the second axis. # 略

In [ ]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.fliplr(my_3_8_array) # is equivalent to slice [:, ::-1] # 略

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [ ]:
my_3_8_array[:, ::-1]

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [ ]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.fliplr(my_2_3_4_array) # is equivalent to slice [:, ::-1, :]. The array flips along the second axis. # 略

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [ ]:
my_2_3_4_array[:, ::-1] # my_2_3_4_array[:, ::-1, :]

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [ ]:
print(my_3_8_array)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
# flip upside down
print(np.flipud(my_3_8_array)) # is equivalent to slice [::-1]. The array flips along the first axis. # 略
print('------------------------')
print(my_3_8_array[::-1]) # my_3_8_array[::-1, :]

[[16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]]
------------------------
[[16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]]


In [ ]:
print(my_2_3_4_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(np.flipud(my_2_3_4_array)) # is equivalent to slice [::-1]. The array flips along the first axis. # 略
print('-------------')
print(my_2_3_4_array[::-1]) # my_2_3_4_array[::-1,:,:]   # [::-1] -> [-1::-1]

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
-------------
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [ ]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
before[::-1] # step=-1

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
before[-1::-1] # step=-1

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
before[-1::] # step=+1

array([[5, 6, 7, 8]])

In [ ]:
before[-1:] # step=+1

array([[5, 6, 7, 8]])

In [ ]:
before[-1] # 1-d

array([5, 6, 7, 8])

In [ ]:
before[-1, :] # 1-d

array([5, 6, 7, 8])

In [ ]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
# rotate 90 degree # 略

np.rot90(my_3_8_array) # rotate in counter-clockwise

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [ ]:
np.rot90(my_3_8_array, k=-1) # rotate in clockwise # 略

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

## Transpose-like operations

In [ ]:
my_start_array = np.arange(24)
my_3_8_array = my_start_array.reshape((3, 8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [ ]:
print(my_start_array)
print('-----')
print(my_start_array.T)
# or
# print(np.transpose(my_start_array))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
print(my_3_8_array)
print('-----')
print(my_3_8_array.T) # # axes (0,1) -> (1,0)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
-----
[[ 0  8 16]
 [ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]]


In [ ]:
print(my_2_3_4_array)
print('-----')
print(np.transpose(my_2_3_4_array, axes=(0,2,1))) # (0,1,2) -> (0,2,1)
print('-----')
print(np.transpose(my_2_3_4_array, axes=(0,1,2))) # no change

# transpose over axes index by 2 and axes index by  1
# axes = By default, reverse the dimensions, 
# otherwise permute the axes according to the values given.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
-----
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
-----
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(my_2_3_4_array) # shape=(2,3,4)
print(np.transpose(my_2_3_4_array, axes=(1,2,0))) # shape=(3,4,2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [ ]:
# excercise 2

# Create 2d array (4*3) (value 1-12)

# 其中大於 5的奇數 + 200


# Create a 10x10 array with random values from the "standard normal" distribution. (numpy.random.randn())

# find the minimum and maximum values


# Create a 5x10 array with numpy.random.randn()

# find the mean of each row

# find the sum of each col

In [ ]:
# excercise 3

# 試以 Numpy 畫棋盤

# 1.周邊 1, 內部 0
# [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 2.周邊 0, 內部 1
# [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 3.棋盤 0, 1 交錯 # 提示 建立0或1部分的Mask
# [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
#  [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
#  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
#  [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
#  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
#  [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
#  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
#  [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
#  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
#  [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]